name: Build Modpack Release

on:
  push:
    branches:
      - dev

jobs:
  build-release-dev:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      discussions: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '26'
          distribution: 'temurin'
          
      - name: Get version from pakku.json
        id: version
        run: |
          VERSION=$(jq -r '.version' pakku.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        
      - name: Build Modpack (CurseForge Profile + Server Pack)
        run: |
          java -jar pakku.jar export
      
      - name: List built files
        run: |
          ls -laR build/

      - name: List built files
        run: |
          mkdir -p build/releasefiles
          mv build/curseforge/EpochX-${{ steps.version.outputs.version }}.zip build/releasefiles/EpochX-${{ steps.version.outputs.version }}-client.zip
          mv build/serverpack/EpochX-${{ steps.version.outputs.version }}.zip build/releasefiles/EpochX-${{ steps.version.outputs.version }}-server.zip
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}-dev
          name: EpochX ${{ steps.version.outputs.version }} - dev
          body: "Automated release from GitHub Actions"
          draft: false
          prerelease: true
          files: |
            build/releasefiles/EpochX-${{ steps.version.outputs.version }}-client.zip
            build/releasefiles/EpochX-${{ steps.version.outputs.version }}-server.zip
